server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-2:8762/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: true