server:
  port: 8762

spring:
  application:
    name: eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: true